### ISSUE TITLE
Hosting of mp3-files

### ISSUE THREAD

**Issue by davidelbe** [standout/webbradion.net#9]
Amazon S3 is not the most user-friendly way to upload the files. 
Can we host them elsewhere?

I guess hosting it on Github pages would consume too much space/bandwidth.

**Comment by rendom** [comment]
Maybe Soundcloud? http://help.soundcloud.com/customer/portal/articles/1209292-can-i-podcast-with-soundcloud-

**Comment by davidelbe** [comment]
@rendom Ja, det låter som ett bra förslag. Jag skaffar ett konto så får vi se. Jag antar att vi går på deras Pro-konto ($9/månad).

**Comment by rendom** [comment]
Vet faktiskt ej om det krävs Pro-konto men inte omöjligt att det går på samma "utrymme" som vanliga soundcloud.
Det är ju i betastadiet fortfarande och har vart det ganska länge nu.

**Comment by davidelbe** [comment]
Har kollat lite på Soundclud, det krävs ett Pro-konto, och det tar en del tid att ladda upp det här. Det jobbigaste är nog att vi inte kan automatisera hela processen på ett smidigt sätt.

@scmx - Du som fixar med servrarna, vad skulle du föredra - fortsätta hosta på Amazon S3 eller köra på någon befintlig server hos Glesys/FS-data?
